### ISSUE TITLE
add AIRS Schema framework for Hours

### ISSUE THREAD

**Issue by spara** [codeforamerica/OpenReferral#13]
The AIRS Schema does include an optional framework for Hours that would help someone finding a Food Pantry that was open on a Thursday (instead of scrolling through 25 food pantries to find one that was open on Thursdays)

**Comment by spara** [comment]
Used schema proposed by Moncef, coincides with Ohana API

**Comment by greggish** [comment]
Can you clarify whether this choice was made to coincide with Ohana API *instead* of the AIRS schema?

**Comment by spara** [comment]
See issue #59 https://github.com/codeforamerica/OpenReferral/issues/59
