### ISSUE TITLE
Create validation tool

### ISSUE THREAD

**Issue by anselmbradford** [codeforamerica/OpenReferral#36]
It would be great to be able to take a set of data, plug it into a tool, and validate it against the OpenReferral spec. Like what http://validator.w3.org/#validate_by_input does for HTML. What do you think about this @spara? This could be a hack-request for the community to build b/c it would live at a different repo no doubt.

**Comment by spara** [comment]
prototype validation tool: https://github.com/niveditc/open-referral-validation

**Comment by greggish** [comment]
That validation tool was for a previous version of this spec, and will need to be rebuilt entirely, so this issue should be re-opened.

**Comment by spara** [comment]
Validation tool is outside the scope of the specification and should be addressed in the validation repo

**Comment by monfresh** [comment]
I agree with Sophia. The tool is related, but is a separate project.

**Comment by niveditc** [comment]
Opened an issue in the validation tool repo – https://github.com/niveditc/open-referral-validation/issues/2
@greggish, @spara  – am I right in using v0.8 of the spec as the basis for rebuilding the tool or is there a newer stable version?
I plan on beginning work on this in a couple of days.

**Comment by greggish** [comment]
Thanks for your patience, @niveditc. V1.0 is long past due but we're expecting it to be posted any moment now (and this repo incorrectly link to an out-of-date v0.8... version 0.9 is [here](https://docs.google.com/document/d/1jbgO92cPAUygQI-0_DtLXrdPQKbPNNIkxDr-3WvdFNE/edit) and in the repo itself).

While we're waiting, if you have additional details about your schedule and anything else you might need to get this done -- let us know! :)
