### ISSUE TITLE
Best way to identify a 24-hour hotline?

### ISSUE THREAD

**Issue by monfresh** [codeforamerica/OpenReferral#41]
There is a need to be able to identify a phone number as being a 24/7 hotline. In terms of querying the data from an app like Ohana API, it would be best if this definition was standardized and fixed.

Options I can think of:
- Add it as a "type" option. If by default, all hotlines are 24/7, then a simple `hotline` type would do.

- Add a new boolean `hotline` field to the Phones table.

Thoughts?

**Comment by spara** [comment]
Up to user to add hotllne enumeration in datapackage.json

**Comment by monfresh** [comment]
This is actually already available in both the spec and Ohana API. In the Phones table, the `number_type` field has several different possible values, and `hotline` is one of them. View them all here: https://github.com/codeforamerica/ohana-api/wiki/Populating-the-Postgres-database-from-OpenReferral-compliant-CSV-files#phonescsv-required
