### ISSUE TITLE
Is there any equivalent of a kind/category of organization in OR? 

### ISSUE THREAD

**Issue by anselmbradford** [codeforamerica/OpenReferral#46]
An organizations can provide multiple services at multiple locations such as hot meals, counseling, shelter, etc., but it's useful to have a single top-level designator for grouping related organizations together. This is helpful in, for example, visually differentiating search results. SMC-Connect (https://github.com/smcgov/SMC-Connect) has a `kind` filter for this purpose, which has been removed from Ohana-Web-Search (https://github.com/codeforamerica/ohana-web-search) to align that project with OR. The difference I see between services and a kind/category is like:

**hot meal**      -->    **a Service** (org can have multiple services at multiple locations)
**food pantry**  -->    **a Kind/Category** (org can only be one kind/category)

An analogy using restaurant-style data would be:

ORG A
**Cocktails**           -->     **Service**
**Drinks on tap**    -->     **Service**
**Bottled drinks**   -->     **Service**
**Bar**                   -->     **Kind**

ORG B
**Sit down meal**   -->   **Service**
**Bottled drinks**   -->    **Service**
**Restaurant**       -->   **Kind**

So the "kind" in this designates the primary purpose of the organization, even though the services are overlapping.

A thought is that a client application could pull out the top-level service taxonomy terms and use those as a kind/category designation. So in the case of an implementation that used the openeligibility.org (OE) taxonomy, that would be 11 top-level categories of service. The problem is these are still attached to the services, so an organization can have multiple top-level services (e.g. Care+Emergency+Food). A possible solution for this could be effectively having 12 top-level categories (the 11 single categories, plus 1 "mixed category" that contained two or more of the other 11).

Another option could be to designate a certain collection of services as describing a kind of organization. So using OE as an example, say an organization has the services `Food > Free Meals` and `Emergency > Emergency Food`. The client application could designate that organization as a "Food Pantry" automatically. Or say an organization has `Housing > Safe Housing` and `Emergency > Emergency Shelter`. That could be labeled as a "Homeless Shelter". A complication with OE is that it mixes what I would interpret as a "kind" of service with the actual service. For instance, http://openeligibility.org/food/ contains "Free Meals" (an actual service) and "Food Pantry" (a kind of service). Does that make sense? The actual service (Free Meal) is part of an umbrella of services provided by a kind of organization (a Food Pantry).

cc @spara @greggish Thoughts/guidance on this?

**Comment by spara** [comment]
Taxonomy is not part of the specification, this is an Ohana API isssue
