### ISSUE TITLE
Importing Spreadsheets into Ohana

### ISSUE THREAD

**Issue by devinbalkind** [codeforamerica/OpenReferral#51]
Hi folks. 

[NYC:Prepared] (http://nycprepared.org) has been converting information about Superstorm Sandy related services into spreadsheet designed to match the OR spec.  That spreadsheet is [here] (https://docs.google.com/a/sarapisfoundation.org/spreadsheet/ccc?key=0ArhSktWsQi1VdDZhSDc5NWtwVm4tVFM3eThxeDA1anc&usp=drive_web#gid=9).

We've got deployments of the [Ohana API Admin] (http://services.nycprepared.org:8081) and [Ohana API Dev Portal] (http://services.nycprepared.org:8080).  

We'd like to get our spreadsheet imported into the data platform and so we can set up the Ohana Web Search tool and get people access to services information!

To achieve this @monfresh advised us to add an issue here.  He also said we should make our spreadsheets more closely resemble the OR spec.  To do that we have a few questions:

* is the spec finalized?
* is each heading on the spec a separate sheet?
* how do we format arrays of strings & arrays of objects?
* do we need to know any taxonomies or do we create our own.  this question is related to fields like legal_status, service_languages, resource_type, etc.

Please let me know if you can help with this task, and/or if you have advice, tools, templates, etc that could be useful.

Thanks.

**Comment by spara** [comment]
This is an Ohana API issue

**Comment by greggish** [comment]
@devinbalkind please let us know whether you have the information you need, especially w/r/t formatting arrays.

**Comment by monfresh** [comment]
The original question @devinbalkind had about formatting arrays of strings and arrays of objects is no longer applicable. Those terms came from the old way of importing data into the API. Ohana API is now fully documented in terms of importing OR-compliant CSV files. You don't have to worry about arrays. You just need to follow the instructions in the Google Spreadsheets template and in the Ohana API Wiki.
