### ISSUE TITLE
Handling multi-paragraph fields

### ISSUE THREAD

**Issue by declan** [codeforamerica/OpenReferral#56]
The specification states in section 5.0 that data fields may not contain new lines or HTML tags. In our dataset, some of the fields can be multi-paragraph (e.g. service descriptions). We also find it useful to let users create lists. For example, I'd like to be rendering the description of [this service](http://pomona-family-resources-stage.herokuapp.com/organizations/salvation-army-3/emergency-lodging?org_name=Salvation+Army) as a list.

I was initially going to open this issue on ohana-web-search, but since that application is intended to consume Open Referral compliant data and Open Referral doesn't allow for newlines, it seemed better to bring it up here first. If there's a better place to be talking about this issue please let me know.

Would you be open to allowing some of the fields to contain data in Markdown format or something similar? Practically speaking, it seems like a two-paragraph-long description of a service wouldn't be uncommon.

**Comment by spara** [comment]
HSDS uses CSV files to hold the data. The CSV specification (linked in the document) allows for newlines
