### ISSUE TITLE
Why is internet resource a separate table?

### ISSUE THREAD

**Issue by monfresh** [codeforamerica/OpenReferral#58]
Is there a particular benefit of having emails and websites be defined in a separate table as opposed to having them as individual fields within the main tables? Just trying to understand the reasoning here. Usually, when there are multiple choices for a field, that choice is the actual value for the field and no other field is necessary. For example, a phone number could be of type TTY. In this case, the `number_type` field could accept two values: "TTY number" or "Not a TTY number".

In the Internet Resource case, you can't just choose from the 3 options: website, email, application. You also have to fill out the actual value in a separate field, which seems redundant in this case. There is no need to have to specify that a particular field is a website versus an email address. Those are so ubiquitous that it's obvious which one is which.

https://github.com/codeforamerica/OpenReferral/blob/master/openreferral.md#internet-resource-internet_resourcecsv

**Comment by spara** [comment]
Removed from spec
