### ISSUE TITLE
Spec as Spreadsheet

### ISSUE THREAD

**Issue by devinbalkind** [codeforamerica/OpenReferral#61]
Hi.  Is this specification available as a spreadsheet?  I offer the following spreadsheet to resource builders in our area: https://docs.google.com/a/sarapisfoundation.org/spreadsheet/ccc?key=0ArhSktWsQi1VdGttQl9ranR0UXNLUGpTMXJhZmhndGc&usp=drive_web#gid=9

Outlining the spec in an actionable spreadsheet would certainly make it easier for me to track changes, and also enable me to share spreadsheet formats (which are the most common) with other folks making resource directories.

Thanks!

**Comment by haileypate** [comment]
Yikes, I missed this! Devin, the goal for the spreadsheet above is more for studying the requirements of the specification. A use case would be if you have some data and you want to see if you have all of the ingredients to be compatible with what the HSDS requires or recommends.

**Comment by spara** [comment]
Moncef and Hailey have provided a spreadsheets: https://docs.google.com/spreadsheets/d/1uUaQROpIkEvmGzcGkdxraqPL-I2K_1Y8E1Gw8U0BPYo/edit#gid=595985385
