### ISSUE TITLE
Language localization

### ISSUE THREAD

**Issue by dhenderson** [codeforamerica/OpenReferral#63]
Text presented back to the end user like "description" on the "organization" table should be translatable to any number of languages. Instead of backing text displayed back to the end user on entities like "organization" and "service", might consider separating text displayed to the end user in a separate table.

For example, the "organization" table might have a corresponding "organization_text" table. "organization_text" would have attributes like "description" as well as a column specifying the language. This schema would allow any number of language translations for each organization/program/service etc.

**Comment by spara** [comment]
Can be extended by user
