### ISSUE TITLE
Align address fields with schema.org

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/OpenReferral#67]
Both physical_address and postal_address have a set of fields that is different from those in the schema.org PostalAddress object (http://schema.org/PostalAddress). What about to use these fields for HSDS addresses?

* street_address
* street_address_2 (not in schema.org)
* address_locality
* address_region
* postal_code
* address_country

These also have the benefit for locality and region of being more general and internationalized than city and state_province.

**Comment by spara** [comment]
The schema documents the fields used for address and that they are derived from best practices taken from the Universal Postal Union. With the exception of the additional address fields, they hew closely to the schema.org unless you mean the field names

**Comment by pmackay** [comment]
I think its ok to leave this if you prefer. Perhaps what could be also
interesting to explore is to map the fields in HSDS to schema.org types,
but that doesnt require changing the name. Thats a separate issue though,
and might relate to editing the datapackage.json file. I've been exporing
that a bit in relation to using csvlint for package validation.

**Comment by spara** [comment]
I'll leave this as is and leave the mapping to schema.org for a later time.

**Comment by greggish** [comment]
Paul, @haileypate has also identified mapping to schema.org as a task for the road ahead. We should make this an issue for future development.
